name: Build Script for Secrets of Summerside

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up C environment
      run: |
        sudo apt update
        sudo apt install -y build-essential libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev

    - name: Build game
      run: 
        make secrets
        
    - name: Build test
      run: 
        make test

    - name: Give permission to test script 
      run: 
        chmod +x ./test_script.sh

    - name: Run test
      run: 
        ./test_script.sh > test_results.txt 

    - name : Generate and upload gcov report
      run: |
        gcov test-checkguess-test.c > percent_report.txt
    
    - name: Upload gcov report
      uses: actions/upload-artifact@v3
      with:
        name: gcov-report
        path: checkguess-test.c.gcov

    - name: Upload game
      uses: actions/upload-artifact@v4
      with:
        name: Secrets of Summerside
        path: secrets

    - name: upload test results
      uses: actions/upload-artifact@v4	
      with:
        name: Test Results			
        path: test_results.txt

    - name: upload percent report for gcov
      uses: actions/upload-artifact@v4	
      with:
        name: percent report for gcov			
        path: percent_report.txt