name: Build Script for Secrets of Summerside

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up C environment
      run: |
        sudo apt update
        sudo apt install -y build-essential libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev

    - name: Set DISPLAY environment variable
      run: |
        export DISPLAY=:0

    - name: Build test
      run: |
        make test

    - name: Run tests
      run: |
        ./test


