name: Build Script for Secrets of Summerside

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build game
      run: 
        make secrets 
        
    - name: Build test
      run: 
        make test

    - name: Give permission to test script 
      run: 
        chmod +x ./test_script.sh

    - name: Run test
      run: 
        ./test_script.sh

    - name : Generate gcov report
      run: |
        make testcoverage 
        gcov checkguess-test.c


